# Generated by Django 5.2.7 on 2025-10-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_challenge_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengemember',
            old_name='Challenge',
            new_name='challenge',
        ),
    ]
