# Generated by Django 5.2.7 on 2025-10-30 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_challenge_challengemember_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='challenges_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challengemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='challengemember',
            unique_together={('challenge', 'user')},
        ),
    ]
