# Generated by Django 5.1.2 on 2025-11-05 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_challenge_winner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedgoal',
            unique_together={('goal', 'challenge_member')},
        ),
    ]
